const assert=require('node:assert/strict');
const S=require('../hotfix-sync.js'),R=require('../js/khsx-hotfix-runtime.js');
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
 let time=100000,context={accountId:'A',deviceId:'D',visible:true,online:true,mode:'normal'},calls=0;
 const queue={};for(let i=0;i<100;i++)queue[i]=S.bindItem({operation_id:String(i)},context,time);
 const s=S.createScheduler({now:()=>time,random:()=>0,getContext:()=>context});
 let outcome={error:{status:503,message:'busy'}};
 const d=[{getItems:()=>queue,persist:()=>true,send:async()=>{calls++;return outcome}}];
 await s.drain(d);assert.equal(calls,1);assert.equal(Object.keys(queue).length,100);
 for(let i=0;i<100;i++)await s.drain(d);assert.equal(calls,1);
 time+=30000;outcome={status:'applied'};await s.drain(d);assert.equal(calls,6);
 context.visible=false;time+=5000;await s.drain(d);assert.equal(calls,6);
 context.visible=true;context.accountId='B';await s.drain(d);assert.equal(calls,6);
 context.accountId='A';context.mode='read_only';await s.drain(d);assert.equal(calls,6);
 console.log('PASS outage stops backlog after one failed send, batches max five, no hidden/cross-account/read-only replay');
 context.mode='normal';let release;const q={x:S.bindItem({operation_id:'old'},context)};
 const s2=S.createScheduler({getContext:()=>context});const p=s2.drain([{getItems:()=>q,persist:()=>true,send:()=>new Promise(r=>release=r)}]);
 await tick();q.x=S.bindItem({operation_id:'new'},context);release({status:'applied'});context.visible=false;await p;
 assert.equal(q.x.operation_id,'new');context.visible=true;
 const conflict={x:S.bindItem({operation_id:'conflict'},context)};
 await S.createScheduler({getContext:()=>context}).drain([{getItems:()=>conflict,persist:()=>true,send:async()=>({status:'conflict',error:{code:'ASSIGNMENT_CONFLICT'}})}]);
 assert.equal(conflict.x.status,'failed');
 let writes=0;await S.createScheduler({getContext:()=>context}).drain([{getItems:()=>q,persist:()=>false,send:async()=>{writes++}}]);assert.equal(writes,0);
 assert.equal(S.normalizeQueue({x:{operation_id:'legacy'}}).x.status,'quarantined');
 assert(S.loadQueue({getItem:()=>'{invalid'},'key').raw);
 assert.notEqual(S.storageKey('x','A','D'),S.storageKey('x','B','D'));
 assert.equal(S.classifyError({code:'PT409'}).kind,'conflict');assert(S.retryDelay(50,()=>1)<=600000);
 console.log('PASS old acknowledgment preserves newer edit; conflicts retained; disk failure blocks send; legacy ownership quarantined');
 let active=0,max=0,releases=[],sent=0;time=100000;
 const transport=R.createTransport({context:()=>context,now:()=>time,random:()=>0,fetch:async()=>{sent++;active++;max=Math.max(max,active);await new Promise(r=>releases.push(r));active--;return new Response('{}')}});
 const jobs=Array.from({length:9},()=>transport.fetch('https://test.invalid/rest/v1/table',{method:'POST'}));
 await tick();assert.equal(sent,1);
 while(releases.length){releases.shift()();await tick();}
 await Promise.all(jobs);assert.equal(max,1);
 const reads=Array.from({length:9},()=>transport.fetch('https://test.invalid/rest/v1/table'));
 await tick();assert.equal(active,3);
 while(releases.length){releases.shift()();await tick();}await Promise.all(reads);assert.equal(max,3);
 let failures=0;const bad=R.createTransport({context:()=>context,now:()=>time,random:()=>0,fetch:async()=>{failures++;return new Response('{}',{status:503})}});
 await bad.fetch('https://test.invalid/rest/v1/table');for(let i=0;i<100;i++)await bad.fetch('https://test.invalid/rest/v1/table');assert.equal(failures,1);
 context.visible=false;time+=30000;await bad.fetch('https://test.invalid/rest/v1/table');assert.equal(failures,1);
 console.log('PASS transport serializes writes, caps reads at three, and blocks 100 repeat requests during cooldown/hidden state');
})().catch(e=>{console.error(e);process.exitCode=1});
